name: Automatic Tests

on:
  - push
  - pull_request

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]
        python-version: ['3.8', '3.7']

    steps:
      - uses: actions/checkout@v2
      - name: Setup up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Upgrading PIP
        run: | 
          python -m pip install --upgrade pip
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          $file = 'requirements.txt'
          if (Test-Path -Path $file)
          {
            pip install -r requirements.txt
          }
      - name: MyPy Tests
        run: |
          mypy .
      - name: MyPy Advanced
        run: |
          mypy --disallow-untyped-defs --disallow-incomplete-defs --check-untyped-defs --no-implicit-optional --warn-redundant-casts --warn-return-any --disallow-untyped-globals --allow-redefinition --show-error-context --show-column-numbers --show-error-codes --pretty --disallow-any-generics .
      - name: PyTest Tests
        run: |
          pytest -vv -s