; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "Quizzing Application 3"
#define MyAppVersion "3.0"
#define MyAppPublisher "Geetansh Gautam"
#define MyAppURL "https://geetanshgautam.wixsite.com/home"
#define SetupEXEName "qa_update_app.exe"

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{F9E57D15-6FBF-43D3-9655-7774A92A4BF9}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={autopf}\{#MyAppName}
DefaultGroupName={#MyAppName}
DisableProgramGroupPage=yes
; Uncomment the following line to run in non administrative install mode (install for current user only.)
;PrivilegesRequired=lowest
PrivilegesRequiredOverridesAllowed=dialog
OutputDir=D:\User Files\OneDrive\Documents\2. Electronics\1. Python\QAS 3-2\installer
OutputBaseFilename=QuizzingAppInstaller
SetupIconFile=D:\User Files\OneDrive\Documents\2. Electronics\1. Python\QAS 3-2\.src\.icons\.app_ico\setup.ico
Compression=lzma
SolidCompression=yes
WizardStyle=modern

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Files]
Source: "D:\User Files\OneDrive\Documents\2. Electronics\1. Python\QAS 3-2\installer\.config\*"; DestDir: "{app}\.config"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "D:\User Files\OneDrive\Documents\2. Electronics\1. Python\QAS 3-2\installer\.qa_update\*"; DestDir: "{app}\.qa_update"; Flags: ignoreversion recursesubdirs createallsubdirs
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Run]
Filename: "{app}\.qa_update\{#SetupEXEName}"; WorkingDir: "{app}"; StatusMsg: "Installing Modules"; Flags: shellexec hidewizard 
; TODO: Add checkbox (post___) for addons
